version: '3'

volumes:
    laravel-redis-data:
    laravel-postgres-data:
    laravel-ws-data:

networks:
    laravel:
        driver: bridge

services:
    api:
        build:
            context: ./docker
            dockerfile: php/Dockerfile
        restart: always
        container_name: "api"
        tty: true
        volumes:
            - ./.:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        links:
            - postgres
            - redis
            - mail
        networks:
            - laravel

    postgres:
        image: postgres:alpine
        container_name: laravel-postgres
        restart: always
        volumes:
            - laravel-postgres-data:/var/lib/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        networks:
            - laravel
        env_file:
            - .env

    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - laravel-redis-data:/redis-data
        networks:
            - laravel
        environment:
            REDIS_HOST: "${REDIS_HOST}"
            REDIS_PASSWORD: "${REDIS_PASSWORD}"
            REDIS_PORT: "${REDIS_PORT}"
        env_file:
            - .env

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        hostname: 'xelon.test'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf:delegated
        depends_on:
            - api
        networks:
            - laravel

    websockets:
        build:
            context: ./docker
            dockerfile: websockets/ws.Dockerfile
            args:
                - PUID=${HOST_PUID}
                - PGID=${HOST_PGID}
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        restart: unless-stopped
        ports:
            - "6001:6001"
        volumes:
            - laravel-ws-data:/ws-data
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ./:/var/www
        expose:
            - "6001"
        depends_on:
            - redis
        env_file:
            - .env
        networks:
            - laravel

    mail:
        image: mailhog/mailhog
        ports:
            - "7025:1025"
            - "7725:8025"
        networks:
            - laravel
